name: FrevoOnRails
highlighter: pygments
permalink: /blog/:year/:month/:day/:title/
permalink: pretty
description: Grupo de desenvolvedores de Ruby / Rails de Pernambuco.
url: http://frevoonrails.com.br
